'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.3053
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 2.0.50727.3053.
'
Namespace org.openehr
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ArchetypeFinderBeanSoap11Binding", [Namespace]:="http://archetypeServlet")>  _
    Partial Public Class ArchetypeFinderBean
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getArchetypeADLURLsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getArchetypesInADLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getArchetypeInADLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDescriptionForArchetypesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getArchetypeIdsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDescriptionForArchetypeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getArchetypeIdsFromPartialIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getArchetypeADLURLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = OceanArchetypeEditor.Instance.Options.RepositoryUrl.ToString
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getArchetypeADLURLsCompleted As getArchetypeADLURLsCompletedEventHandler
        
        '''<remarks/>
        Public Event getArchetypesInADLCompleted As getArchetypesInADLCompletedEventHandler
        
        '''<remarks/>
        Public Event getArchetypeInADLCompleted As getArchetypeInADLCompletedEventHandler
        
        '''<remarks/>
        Public Event getDescriptionForArchetypesCompleted As getDescriptionForArchetypesCompletedEventHandler
        
        '''<remarks/>
        Public Event getArchetypeIdsCompleted As getArchetypeIdsCompletedEventHandler
        
        '''<remarks/>
        Public Event getDescriptionForArchetypeCompleted As getDescriptionForArchetypeCompletedEventHandler
        
        '''<remarks/>
        Public Event getArchetypeIdsFromPartialIdCompleted As getArchetypeIdsFromPartialIdCompletedEventHandler
        
        '''<remarks/>
        Public Event getArchetypeADLURLCompleted As getArchetypeADLURLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getArchetypeADLURLs", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getArchetypeADLURLs(<System.Xml.Serialization.XmlElementAttribute("archetypeIds", IsNullable:=true)> ByVal archetypeIds() As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String()
            Dim results() As Object = Me.Invoke("getArchetypeADLURLs", New Object() {archetypeIds})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getArchetypeADLURLsAsync(ByVal archetypeIds() As String)
            Me.getArchetypeADLURLsAsync(archetypeIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getArchetypeADLURLsAsync(ByVal archetypeIds() As String, ByVal userState As Object)
            If (Me.getArchetypeADLURLsOperationCompleted Is Nothing) Then
                Me.getArchetypeADLURLsOperationCompleted = AddressOf Me.OngetArchetypeADLURLsOperationCompleted
            End If
            Me.InvokeAsync("getArchetypeADLURLs", New Object() {archetypeIds}, Me.getArchetypeADLURLsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetArchetypeADLURLsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getArchetypeADLURLsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getArchetypeADLURLsCompleted(Me, New getArchetypeADLURLsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getArchetypesInADL", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getArchetypesInADL(<System.Xml.Serialization.XmlElementAttribute("archetypeIds", IsNullable:=true)> ByVal archetypeIds() As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String()
            Dim results() As Object = Me.Invoke("getArchetypesInADL", New Object() {archetypeIds})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getArchetypesInADLAsync(ByVal archetypeIds() As String)
            Me.getArchetypesInADLAsync(archetypeIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getArchetypesInADLAsync(ByVal archetypeIds() As String, ByVal userState As Object)
            If (Me.getArchetypesInADLOperationCompleted Is Nothing) Then
                Me.getArchetypesInADLOperationCompleted = AddressOf Me.OngetArchetypesInADLOperationCompleted
            End If
            Me.InvokeAsync("getArchetypesInADL", New Object() {archetypeIds}, Me.getArchetypesInADLOperationCompleted, userState)
        End Sub
        
        Private Sub OngetArchetypesInADLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getArchetypesInADLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getArchetypesInADLCompleted(Me, New getArchetypesInADLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getArchetypeInADL", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getArchetypeInADL(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal archetypeId As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("getArchetypeInADL", New Object() {archetypeId})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getArchetypeInADLAsync(ByVal archetypeId As String)
            Me.getArchetypeInADLAsync(archetypeId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getArchetypeInADLAsync(ByVal archetypeId As String, ByVal userState As Object)
            If (Me.getArchetypeInADLOperationCompleted Is Nothing) Then
                Me.getArchetypeInADLOperationCompleted = AddressOf Me.OngetArchetypeInADLOperationCompleted
            End If
            Me.InvokeAsync("getArchetypeInADL", New Object() {archetypeId}, Me.getArchetypeInADLOperationCompleted, userState)
        End Sub
        
        Private Sub OngetArchetypeInADLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getArchetypeInADLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getArchetypeInADLCompleted(Me, New getArchetypeInADLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getDescriptionForArchetypes", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDescriptionForArchetypes(<System.Xml.Serialization.XmlElementAttribute("archetypeIds", IsNullable:=true)> ByVal archetypeIds() As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal language As String, <System.Xml.Serialization.XmlElementAttribute("descriptionTerms", IsNullable:=true)> ByVal descriptionTerms() As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String()
            Dim results() As Object = Me.Invoke("getDescriptionForArchetypes", New Object() {archetypeIds, language, descriptionTerms})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDescriptionForArchetypesAsync(ByVal archetypeIds() As String, ByVal language As String, ByVal descriptionTerms() As String)
            Me.getDescriptionForArchetypesAsync(archetypeIds, language, descriptionTerms, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDescriptionForArchetypesAsync(ByVal archetypeIds() As String, ByVal language As String, ByVal descriptionTerms() As String, ByVal userState As Object)
            If (Me.getDescriptionForArchetypesOperationCompleted Is Nothing) Then
                Me.getDescriptionForArchetypesOperationCompleted = AddressOf Me.OngetDescriptionForArchetypesOperationCompleted
            End If
            Me.InvokeAsync("getDescriptionForArchetypes", New Object() {archetypeIds, language, descriptionTerms}, Me.getDescriptionForArchetypesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDescriptionForArchetypesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDescriptionForArchetypesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDescriptionForArchetypesCompleted(Me, New getDescriptionForArchetypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getArchetypeIds", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getArchetypeIds(<System.Xml.Serialization.XmlElementAttribute("searchParams", IsNullable:=true)> ByVal searchParams() As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String()
            Dim results() As Object = Me.Invoke("getArchetypeIds", New Object() {searchParams})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getArchetypeIdsAsync(ByVal searchParams() As String)
            Me.getArchetypeIdsAsync(searchParams, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getArchetypeIdsAsync(ByVal searchParams() As String, ByVal userState As Object)
            If (Me.getArchetypeIdsOperationCompleted Is Nothing) Then
                Me.getArchetypeIdsOperationCompleted = AddressOf Me.OngetArchetypeIdsOperationCompleted
            End If
            Me.InvokeAsync("getArchetypeIds", New Object() {searchParams}, Me.getArchetypeIdsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetArchetypeIdsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getArchetypeIdsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getArchetypeIdsCompleted(Me, New getArchetypeIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getDescriptionForArchetype", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDescriptionForArchetype(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal archetypeId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal language As String, <System.Xml.Serialization.XmlElementAttribute("descriptionTerms", IsNullable:=true)> ByVal descriptionTerms() As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String()
            Dim results() As Object = Me.Invoke("getDescriptionForArchetype", New Object() {archetypeId, language, descriptionTerms})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDescriptionForArchetypeAsync(ByVal archetypeId As String, ByVal language As String, ByVal descriptionTerms() As String)
            Me.getDescriptionForArchetypeAsync(archetypeId, language, descriptionTerms, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDescriptionForArchetypeAsync(ByVal archetypeId As String, ByVal language As String, ByVal descriptionTerms() As String, ByVal userState As Object)
            If (Me.getDescriptionForArchetypeOperationCompleted Is Nothing) Then
                Me.getDescriptionForArchetypeOperationCompleted = AddressOf Me.OngetDescriptionForArchetypeOperationCompleted
            End If
            Me.InvokeAsync("getDescriptionForArchetype", New Object() {archetypeId, language, descriptionTerms}, Me.getDescriptionForArchetypeOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDescriptionForArchetypeOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDescriptionForArchetypeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDescriptionForArchetypeCompleted(Me, New getDescriptionForArchetypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getArchetypeIdsFromPartialId", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getArchetypeIdsFromPartialId(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal archetypeIdPart As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String()
            Dim results() As Object = Me.Invoke("getArchetypeIdsFromPartialId", New Object() {archetypeIdPart})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getArchetypeIdsFromPartialIdAsync(ByVal archetypeIdPart As String)
            Me.getArchetypeIdsFromPartialIdAsync(archetypeIdPart, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getArchetypeIdsFromPartialIdAsync(ByVal archetypeIdPart As String, ByVal userState As Object)
            If (Me.getArchetypeIdsFromPartialIdOperationCompleted Is Nothing) Then
                Me.getArchetypeIdsFromPartialIdOperationCompleted = AddressOf Me.OngetArchetypeIdsFromPartialIdOperationCompleted
            End If
            Me.InvokeAsync("getArchetypeIdsFromPartialId", New Object() {archetypeIdPart}, Me.getArchetypeIdsFromPartialIdOperationCompleted, userState)
        End Sub
        
        Private Sub OngetArchetypeIdsFromPartialIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.getArchetypeIdsFromPartialIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getArchetypeIdsFromPartialIdCompleted(Me, New getArchetypeIdsFromPartialIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getArchetypeADLURL", RequestNamespace:="http://archetypeServlet", ResponseNamespace:="http://archetypeServlet", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getArchetypeADLURL(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal archetypeId As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("getArchetypeADLURL", New Object() {archetypeId})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getArchetypeADLURLAsync(ByVal archetypeId As String)
            Me.getArchetypeADLURLAsync(archetypeId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getArchetypeADLURLAsync(ByVal archetypeId As String, ByVal userState As Object)
            If (Me.getArchetypeADLURLOperationCompleted Is Nothing) Then
                Me.getArchetypeADLURLOperationCompleted = AddressOf Me.OngetArchetypeADLURLOperationCompleted
            End If
            Me.InvokeAsync("getArchetypeADLURL", New Object() {archetypeId}, Me.getArchetypeADLURLOperationCompleted, userState)
        End Sub
        
        Private Sub OngetArchetypeADLURLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getArchetypeADLURLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getArchetypeADLURLCompleted(Me, New getArchetypeADLURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getArchetypeADLURLsCompletedEventHandler(ByVal sender As Object, ByVal e As getArchetypeADLURLsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getArchetypeADLURLsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getArchetypesInADLCompletedEventHandler(ByVal sender As Object, ByVal e As getArchetypesInADLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getArchetypesInADLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getArchetypeInADLCompletedEventHandler(ByVal sender As Object, ByVal e As getArchetypeInADLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getArchetypeInADLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getDescriptionForArchetypesCompletedEventHandler(ByVal sender As Object, ByVal e As getDescriptionForArchetypesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDescriptionForArchetypesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getArchetypeIdsCompletedEventHandler(ByVal sender As Object, ByVal e As getArchetypeIdsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getArchetypeIdsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getDescriptionForArchetypeCompletedEventHandler(ByVal sender As Object, ByVal e As getDescriptionForArchetypeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDescriptionForArchetypeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getArchetypeIdsFromPartialIdCompletedEventHandler(ByVal sender As Object, ByVal e As getArchetypeIdsFromPartialIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getArchetypeIdsFromPartialIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getArchetypeADLURLCompletedEventHandler(ByVal sender As Object, ByVal e As getArchetypeADLURLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getArchetypeADLURLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
